---
- name: Install and start Apache on CentOS
  hosts: all
  become: yes
  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is started
      service:
        name: httpd
        state: started
        enabled: yes




